import Head from "next/head";
import { Inter } from "@next/font/google";
import { Container, Stack } from "@mui/material";
import RegisterForm from "@/components/RegisterForm";
import styles from "@/styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome to Crombie-Social</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Stack direction={"row"} alignItems={"center"} sx={{ height: "100vh" }}>
          <Stack sx={{ display: { lg: "block", sm: "none", xs: "none" } }}>
            <img className={styles.landing_img} src="/c27bb43.svg" />
          </Stack>
          <Container>
            <RegisterForm />
          </Container>
        </Stack>
      </main>
    </>
  );
}
